---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "11.10.4"

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[slack_handler]
    attributes:
      chef_client:
        handler: { slack: { team: foo, api_key: bar } }

